server:
  brand: "SwordCraft"
  address: "0.0.0.0"
  reconnect-delay: 2 # In seconds (0 to disable)
  port: 25565
  online-mode: true
  max-players: 20
  motd: "<gradient:#ff0000:#ffff00> SwordCraft </gradient>"

spawn:
  x: 2500.0
  y: 64.0
  z: 2500.0

# Needs to be formatted properly
# filler-one: "minecraft:black_stained_glass_pane"
# filler-two: "minecraft:gray_stained_glass_pane"
gui:
  filler-one: "minecraft:black_stained_glass_pane"
  filler-two: "minecraft:gray_stained_glass_pane"